Week.create(number: 1)
Week.create(number: 2) 
Week.create(number: 3)
Week.create(number: 4) 
Week.create(number: 5) 
Week.create(number: 6) 
Week.create(number: 7) 
Week.create(number: 8) 
Week.create(number: 9) 
Week.create(number: 10) 
Week.create(number: 11) 
Week.create(number: 12) 
Week.create(number: 13) 
Week.create(number: 14) 
Week.create(number: 15) 
Week.create(number: 16) 
Week.create(number: 17)

Team.create(name: "Baltimore Ravens")
Team.create(name: "Cincinnati Bengals")
Team.create(name: "Cleveland Browns")
Team.create(name: "Pittsburgh Steelers")
Team.create(name: "Houston Texans")
Team.create(name: "Indianapolis Colts")
Team.create(name: "Jacksonville Jaguars")
Team.create(name: "Tennessee Titans") 
Team.create(name: "Buffalo Bills")
Team.create(name: "Miami Dolphins") 
Team.create(name: "New England Patriots")
Team.create(name: "New York Jets")
Team.create(name: "Denver Broncos") 
Team.create(name: "Kansas City Chiefs") 
Team.create(name: "Oakland Raiders") 
Team.create(name: "San Diego Chargers") 
Team.create(name: "Chicago Bears")
Team.create(name: "Detroit Lions")
Team.create(name: "Green Bay Packers") 
Team.create(name: "Minnesota Vikings") 
Team.create(name: "Atlanta Falcons") 
Team.create(name: "Carolina Panthers") 
Team.create(name: "New Orleans Saints") 
Team.create(name: "Tampa Bay Buccaneers")
Team.create(name: "Dallas Cowboys") 
Team.create(name: "New York Giants") 
Team.create(name: "Philadelphia Eagles") 
Team.create(name: "Washington Redskins") 
Team.create(name: "Arizona Cardinals") 
Team.create(name: "Los Angeles Rams") 
Team.create(name: "San Francisco 49ers", name: "Seattle Seahawks")